no_metadata = true
async_upload = true
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
caption_extension = ".txt"
dynamo_backend = "no"
enable_bucket = true
gradient_checkpointing = true
low_vram = false

###### huggingface ######
huggingface_path_in_repo = "checkpoint"
huggingface_repo_id = ""
huggingface_repo_type = "model"
huggingface_repo_visibility = "public"
huggingface_token = ""

max_bucket_reso = 2048
max_data_loader_n_workers = 2
max_grad_norm = 1.0
max_token_length = 75
min_bucket_reso = 256
mixed_precision = "fp16"
no_half_vae = true
output_dir = "test_sdxl_sd3"
output_name = "last"
pretrained_model_name_or_path = ""
prior_loss_weight = 1.0
resolution = "1024,1024"
sample_prompts = ""
sample_sampler = "euler_a"
save_model_as = "safetensors"
save_precision = "fp16"
full_fp16 = false
train_data_dir = "img"
training_comment = ""
xformers = true

###### steps and epochs ######
max_train_epochs = 43
save_every_n_epochs = 11

###### loss function ######
loss_type = "huber"
huber_c = 0.1
huber_schedule = "snr"
huber_scale = 1.0
zero_terminal_snr = true
debiased_estimation_loss = true

###### batch size ######
train_batch_size = 4
gradient_accumulation_steps = 1

###### optimizer ######
optimizer_type = "adamw8bit"
optimizer_args = ["weight_decay=0.01", "eps=1e-8"]
unet_lr = 4e-4
text_encoder_lr = 4e-5

###### lr scheduler ######
lr_scheduler = "cosine"

###### noise offset ######
noise_offset_type = "Original"
noise_offset = 0.05

###### misc ######
network_alpha = 16
network_dim = 32
network_module = "networks.lora"
network_args = []
network_dropout = 0
caption_dropout_rate = 0
clip_skip = 1
max_timestep = 1000
min_snr_gamma = 1
scale_weight_norms = 1
seed = 2951032222
